package by.epam.java.training.servise.validation;

public enum ValidatorType {
    SIGN_IN_FORM_VALIDATOR,
    SIGN_UP_FORM_VALIDATOR,
    LOGIN_VALIDATOR,

    LOCALE_VALIDATOR,
    ID_VALIDATOR,
    STRING_VALIDATOR,
    DOUBLE_VALIDATION,

    BOOKMARK_VALIDATOR,
    NEW_BOOKMARK_VALIDATOR,

    PAGES_VALIDATOR,

    TRANSLATED_NEWS_VALIDATOR,
    NEWS_VALIDATOR,

    TRANSLATED_BOOK_VALIDATOR,
    BOOK_VALIDATOR,

}
